= S3 - Simple Storage Service
:toc: left
:sourcedir: /Users/curri/projects/aws/s3
:source-highlighter: pygments

AWS S3 allows us to store and retrieve files in the cloud; we have cheap and virtually unlimited space.

S3 stores files in *buckets*, which have a globally-unique name; we can create a bucket using cloudformation; 

== creating the bucket

The simplest cloudformation template would just define one resource, of type `AWS::S3::Bucket`. The only required property is `BucketName`, which is a globally unique name (S3 is one of the oldest AWS services, and they went with global names, rather than per-account). 

So, a simple CF template would look like: (remember the bucket name has to be unique, so replace it with a name of your own if you run this). 

[source,YAML]
.Simplest yml bucket
----
include::{sourcedir}/SimplestBucket.yml[]
----

== Downloading a file
[source,Groovy]
.download.groovy
----
include::{sourcedir}/download.groovy[]
----

== Uploading a file
[source,groovy]
.download.groovy
----
include::{sourcedir}/upload.groovy[]
----

== Bucket with web configuration and authorization for everybody to read
[source,YAML]
.Bucket with web configuration and a policy allowing anybody to read 
----
include::{sourcedir}/FirstBucket.yml[]
----

== Listing all files in a bucket

S3 does not really 
[source,Groovy]
.ls.groovy
----
include::{sourcedir}/ls.groovy[]
----
