AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 Bucket
Metadata:
  Author: Orlando Karam
  Team: CurriculumDevelopment
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
      - experiment
      - uat
    Default: experiment

Mappings:
  buckets:
    dev:
      BucketName: karamo-dev-bucket
    prod:
      BucketName: karamo-prod-bucket
    experiment:
      BucketName: karamo-simple-s3-bucket

Resources:
  FirstS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap ['buckets', !Ref Environment, 'BucketName']
      