AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 Bucket
Metadata:
  Author: Orlando Karam
  Team: CurriculumDevelopment
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
      - experiment
      - uat
    Default: experiment
Resources:
  FirstS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: karamo-simple-s3-bucket
