Resources:
  DummySQSQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      DelaySeconds: 0               # How long to delay messages

Outputs:
  SpringEnvironment: 
    Value: "prod"
    Export: 
      Name: SpringEnvironment
  ChefEnvironment: 
    Value: "prd"
    Export:
      Name: ChefEnvironment
  DummyQueueArn:
    Value: !GetAtt DummySQSQueue.Arn
    Export:
      Name: DummyQueueArn